version: "3"

tasks:
  init:
    cmds:
      - pnpm prisma init

  migrate:
    cmds:
      - pnpm prisma migrate dev --name init

  generate:
    cmds:
      - pnpm prisma generate

  deploy-migrate:
    cmds:
      - pnpm prisma migrate deploy

  reset:
    cmds:
      - pnpm prisma migrate reset

  seed:
    cmds:
      - pnpm prisma db seed

  studio:
    cmds:
      - pnpm prisma studio

  setup:
    cmds:
      - pnpm prisma init
      - pnpm prisma migrate dev --name init
      - pnpm prisma generate
      - pnpm prisma db seed
